config/routes.rb
Rails.application.routes.draw do

  # run 'rails routes' to see what rails thinks are the routes

  root 'static_pages#a1_top'

  # you can refer to the url '/blah' in code using the method blah_path,
  # without worrying about the actual controller/action names, which are
  # defined here:
  get '/company', to: 'static_pages#b1_company'
  get '/service', to: 'static_pages#b2_service'
  get '/recruit', to: 'static_pages#b3_recruit'
  get '/terms',   to: 'static_pages#b4_terms'
  get '/privacy', to: 'static_pages#b5_privacy'
  
  get '/signup',  to: 'users#new'
  
  # get the full RESTful paths.
  resources :users
  resources :teachers
  resources :lessons
  
  get '/students', to: 'users#index_students'
  post '/buy',     to: 'users#buy'
  post '/book',    to: 'lessons#book'

  # for sessions, we don't want the entire RESTful resources, just a few
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token  # does not exist in database
  has_one :teacher_info
  has_many :lessons, class_name: "Lesson", foreign_key: "teacher_id"
  has_many :bookings, dependent: :destroy
  
  # this allows me to save teacher_info through this class.
  #accepts_nested_attributes_for :teacher_info
  
  # store all emails in lower case
  before_save { email.downcase! }
  
  validates :name, presence: true, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  
  validates :credits, numericality: true

  # Most of the secure password machinery is implemented using this single Rails method 
  has_secure_password
  
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  validates :time_zone, presence: true, allow_nil: false
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token. Used for cookie authentication and password resets.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # arrange to remember a user the next time they log in
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user , only: [:index, :edit, :update, :destroy]
  before_action :correct_user,    only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  # all users (students, teachers, admins)
  def index
    @users = User.paginate(page: params[:page])
  end
  
  # display only students
  def index_students
    @users = User.where(student: true).order(name: :asc).paginate(page: params[:page])
  end  
  
  def show
    @user = User.find(params[:id])
  end



  def new
    @user = User.new
    @user.time_zone = nil
  end
  
  def create
    @user = User.new(user_params)
    @user.credits = 0
    @user.student = true
    
    if @user.save
      # Handle a successful save.
      log_in @user
      flash[:success] = "Welcome to Japaneasy!"
      redirect_to user_url(@user)
    else
      render 'new'
    end
  end
  
  
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      # Handle a successful update
      flash[:success] = "Profile updated"
      redirect_to user_url(@user)
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  def buy
    @user = User.find(params[:user_id])
    quantity = params[:quantity].to_i
    @user.credits += quantity
    @user.save!
    
    respond_to do |format|
      format.js
    end
  end

  
  private
  # rails is now stricter about what params it passes on from forms.
  # you have to explicitly state which params you need.
  # this is called "strong parameters".
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :time_zone)
    end
    
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
    
    
end

app/helpers/users_helper.rb
module UsersHelper
  
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]

    # url-encoded path to public default avatar
    #default = 'http%3A%2F%2Fjapaneasy.me%2Fimages%2Favi-default-160px.png'
    # a geometric shape that is unique to the email hash
    #default = "identicon"
    # mm: mystery man
    default = "mm"

    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=#{default}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/users/_form.html.erb
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', placeholder: "John Smith" %>
      
      <!-- the drop-down (called select in html) for the time zones -->
      <%= f.label :time_zone %>
      <%= f.time_zone_select :time_zone, nil, include_blank: true %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control', placeholder: "john.smith@gmail.com" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>

app/views/users/buy.js.erb
// Ajax magic used to update the two places where credit is displayed
$('#whoami').html("<%=j render('whoami', who: @user) %>");
$('#creditcounter').html("<%=j @user.credits.to_s %>");

app/views/users/edit.html.erb
<% provide(:title, 'Edit student') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All students') %>
<h1>All users</h1>

<!-- The will_paginate method is a little magical; inside a users view, it
automatically looks for an @users object, and then displays pagination links to access
other pages. -->
<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <!-- <%= gravatar_for user, size: 50 %> -->
      <%= link_to user.name, user %>
      <% if current_user.admin? && !current_user?(user) %>
        | <%= link_to "delete", user, method: :delete,
                                      data: { confirm: "You sure?" } %>
      <% end %>
    </li>
  <% end %>
</ul>

<!-- put pagination links at the bottom of the page, too -->
<%= will_paginate %>

app/views/users/index_students.html.erb
<% provide(:title, 'All students') %>
<h1>All students</h1>

<!-- The will_paginate method is a little magical; inside a users view, it
automatically looks for an @users object, and then displays pagination links to access
other pages. -->
<%= will_paginate %>

<ul class="users">
  <% @users.each do |student| %>
    <li>
      <!-- <%= gravatar_for student, size: 50 %> -->
      <%= link_to student.name, student %>
      <% if current_user.admin? && !current_user?(student) %>
        | <%= link_to "delete", student, method: :delete,
                                      data: { confirm: "You sure?" } %>
      <% end %>
    </li>
  <% end %>
</ul>

<!-- put pagination links at the bottom of the page, too -->
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>

Already have an account?
<%= link_to "Log in", login_path %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  <%= @user.name %> <br/>
</h1>
<% if @user.id == current_user.id %>
  
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="col-sm-6">
        <%= @user.email %>
      </div>
        <%= link_to "Edit profile", edit_user_path(@user), class: "btn btn-info" %>
    </div>
  </div>

  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Lesson Credits</h3>
    </div>
    <div class="panel-body">
      <div class="col-sm-6">
        Avilable Credits: <span id="creditcounter" class="badge"><%= @user.credits.to_s %></span>
      </div>
      
      <div class="col-sm-3">      
        <p>Buy 5 lesson credits for ¥5000</p>
      </div>
      
      <div class="col-sm-3">      
        <!-- PayPal button -->
        <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
          <input type="hidden" name="cmd" value="_s-xclick">
          <input type="hidden" name="hosted_button_id" value="FJEE4M7D7YSAS">
          <input type="image" src="https://www.paypalobjects.com/en_US/JP/i/btn/btn_buynowCC_LG.gif" 
            border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
          <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
        </form>
      </div>
      
      <% if Rails.env.development? %>
      <div class="col-sm-3">      
        <%= button_to "+1 CREDIT", buy_path(user_id: @user, quantity: 1), remote: true, class: "btn btn-danger" %>
      </div>
      <div class="col-sm-3">      
        <%= button_to "+5 CREDITS", buy_path(user_id: @user, quantity: 5), remote: true, class: "btn btn-danger" %>
      </div>
      <% end %>
      
    </div>
  </div>
<% end %>