config/routes.rb
Rails.application.routes.draw do

  # run 'rails routes' to see what rails thinks are the routes

  root 'static_pages#a1_top'

  # you can refer to the url '/blah' in code using the method blah_path,
  # without worrying about the actual controller/action names, which are
  # defined here:
  get '/company', to: 'static_pages#b1_company'
  get '/service', to: 'static_pages#b2_service'
  get '/recruit', to: 'static_pages#b3_recruit'
  get '/terms',   to: 'static_pages#b4_terms'
  get '/privacy', to: 'static_pages#b5_privacy'
  
  get '/signup',  to: 'users#new'
  
  # get the full RESTful paths.
  resources :users
  resources :teachers
  resources :lessons
  
  get '/students', to: 'users#index_students'
  post '/buy',     to: 'users#buy'
  post '/book',    to: 'lessons#book'

  # for sessions, we don't want the entire RESTful resources, just a few
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :logged_in_user,  only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user,    only: [:edit, :update]
  before_action :admin_user,      only: [:new, :create, :destroy]

  def index
    @teachers = User.where(teacher: true)
  end
  
  def show
    @user = User.find(params[:id])
    @teacher_info = @user.teacher_info
    @lessons = @user.lessons.where("starts_at > :now", {now: Time.current})
  end
  

  def new
    @user = User.new
    @user.time_zone = nil
    @teacher_info = TeacherInfo.new
    @form_url = teachers_path
  end
  
  def create
    @user = User.new(user_params)
    @teacher_info = TeacherInfo.new(teacher_info_params)
    
    @user.teacher_info = @teacher_info
    @user.credits = 0
    @user.teacher = true  # flag new user as a teacher
    
    # save user and teacher_info to db (note: only need to save user: the association will handle saving teacherinfo, and giving it the correct user_id)
    if @user.save
      flash[:success] = "Teacher created."
      redirect_to teachers_url
    else
      @form_url = teachers_path
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
    @teacher_info = @user.teacher_info
    @form_url = teacher_path
  end
  
  def update
    
    # very nasty code. Need to tidy this up!
    if @user.update_attributes(user_params) && 
        @user.teacher_info.update_attributes(teacher_info_params)
      # Handle a successful update
      flash[:success] = "Profile updated"
      redirect_to teacher_url(@user)
    else
      @teacher_info = @user.teacher_info
      @form_url = teacher_path
      render 'edit'
    end
    
  end
  
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Teacher deleted"
    redirect_to teachers_url
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, 
    :password, :password_confirmation, :time_zone)
  end
  def teacher_info_params
    params.require(:teacher_info).permit(:profile, :message, :yt_vid_1, :yt_vid_2, :yt_vid_3)
  end
  
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
  
  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user) || current_user.admin?
  end
  
  # Confirms an admin user.
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
    
  
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<!-- Rails uses POST if @user.new_record? is true and PATCH if it is false. -->

    <%= form_for(@user, url: @form_url) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', placeholder: "Taro Suzuki" %>
      
      <!-- the drop-down (called select in html) for the time zones -->
      <%= f.label :time_zone %>
      <%= f.time_zone_select :time_zone, nil, include_blank: true %>
        
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control', placeholder: "taro.suzuki@gmail.com"  %>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= fields_for @teacher_info do |ti| %>
        <%= ti.label :profile %>
        <p>NOTE: you can use some <a href="http://www.w3schools.com" target="_blank">HTML tags</a> like <em>a</em>, <em>em</em>, <em>strong</em>, <em>ul</em>...</p>
        <%= ti.text_area :profile, size: "60x6" %>
        <%= ti.label :message %>
        <p>NOTE: you can use some <a href="http://www.w3schools.com" target="_blank">HTML tags</a> like <em>a</em>, <em>em</em>, <em>strong</em>, <em>ul</em>...</p>
        <p>Please add some contact information like email or skype handle so that students can get hold of you if they have any questions.</p>
        <%= ti.text_area :message, size: "60x6" %>
        
        <p>If you have any YouTube self-introduction videos, you can paste the URL of your videos here.</p>
        <%= ti.label "YouTube video URL 1" %>
        <%= ti.url_field :yt_vid_1, class: 'form-control', placeholder: "https://www.youtube.com/watch?v=iqKdEhx-dD4" %>
        <%= ti.label "YouTube video URL 2" %>
        <%= ti.url_field :yt_vid_2, class: 'form-control' %>
        <%= ti.label "YouTube video URL 3" %>
        <%= ti.url_field :yt_vid_3, class: 'form-control' %>
        
      <% end %>
        
      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>

app/views/teachers/_lessons.html.erb
    <%= "#{@lessons.count} upcoming lessons" %> <br/>
    <table>
      <tr>
        <th>Start time</th>
        <th>Duration</th>
        <th>Capacity</th>
        <th>Place available?</th>
      </tr>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.starts_at %></td>
        <td><%= lesson.duration %></td>
        <td><%= lesson.capacity %></td>
        <td><%= lesson.full? ? "NO" : "YES" %></td>
        
        <td>
        <% if current_user.student? %>
          <% if lesson.full? %>
          <%= "Lesson full"  %>
          <% else %>
          <%= button_to "Book lesson", book_path(lesson: lesson), method: :post,
                                        data: { confirm: "One credit will be deducted from your account. Click OK to book this lesson." }, 
                                        class: "btn btn-danger" %>
          <% end %>
        <% end %>
        </td>
        
        <td>
        <!-- only show DELETE link for admins and for the teacher that created the lesson -->
        <% if current_user.admin? || (current_user == lesson.teacher) %>
          
          <%= button_to "Delete lesson", lesson_path(lesson), method: :delete,
                                      data: { confirm: "You sure?" }, 
                                      class: "btn btn-danger",
                                      disabled: (lesson.num_bookings > 0) %>
        <% end %>
        </td>
      </tr>
    <% end %>
    </table>

app/views/teachers/edit.html.erb
<% provide(:title, 'Edit Teacher') %>
<% provide(:button_text, 'Save Changes') %>
<h1>Update your profile</h1>

<div class="gravatar_edit">
  <%= gravatar_for @user %>
  <a href="http://gravatar.com/emails" target="_blank">Change</a>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/teachers/index.html.erb
<% provide(:title, 'All teachers') %>
<h1>Teachers</h1>


<% if logged_in? && current_user.admin? %>
  <%= link_to "Create new Teacher", new_teacher_path %>
<% end %>

<ul class="users">
  <% @teachers.each do |teacher| %>
    <li>
      <%= gravatar_for teacher, size: 50 %>
      <%= link_to teacher.name, teacher_path(teacher) %>      
      
      <% if logged_in? && current_user.admin? %>
        | <%= link_to "edit", edit_teacher_path(teacher.id) %>
      <% end %>
      
      <% if logged_in? && current_user.admin? && !current_user?(teacher) %>
        | <%= link_to "delete", teacher_path(teacher), method: :delete,
                                      data: { confirm: "You sure?" } %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/teachers/new.html.erb
<% provide(:title, 'New Teacher') %>
<% provide(:button_text, 'Register This Teacher') %>
<h1>Register New Teacher</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/teachers/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  <%= @user.name %> <br/>
</h1>

<% if logged_in? && (@user.id == current_user.id || current_user.admin?) %>
  <div class="panel panel-default">
    <div class="panel-body">
        <%= link_to "Edit profile", edit_teacher_path(@user), class: "btn btn-info" %>
        <%= link_to "Add New Lesson", 
          {controller: "lessons", action: "new", teacher_id: @user.id}, 
          class: "btn btn-info" %>
    </div>
  </div>
  
  
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Lesson Credits</h3>
    </div>
    <div class="panel-body">
      <div class="col-sm-6">
        Total Credits: <span class="badge"><%= @user.credits.to_s %></span>
      </div>
      
    </div>
  </div>
<% end %>

<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-xs-4">
        <%= gravatar_for @user, size: 120 %>
      </div>
    
      <div class="col-xs-8">
        <div>
          Profile:
        </div>
        <div>
          <%= sanitize(@teacher_info.profile, tags: ["ul", "ol", "li", "strong", "em", "a", "br", "p"], attributes: ["href", "target"]) if @teacher_info %>
        </div>

        <div>
          Message:
        </div>

        <div>
          <%= sanitize(@teacher_info.message, tags: ["ul", "ol", "li", "strong", "em", "a", "br", "p"], attributes: ["href", "target"]) if @teacher_info %>
        </div>
      </div>
      
    </div>

    
    <% unless @teacher_info.yt_vid_1.nil? || @teacher_info.yt_vid_1.empty? %>
    <div class="row">
      <%= 
      url = parse_youtube(@teacher_info.yt_vid_1)
      content_tag(:iframe, nil, src: "https://www.youtube.com/embed/#{url}?rel=0", width: 560, height: 315, frameborder: 0, allowfullscreen: true) 
      %>
    </div>
    <% end %>
    
    <% unless @teacher_info.yt_vid_2.nil? || @teacher_info.yt_vid_2.empty? %>
    <div class="row">
      <%= 
      url = parse_youtube(@teacher_info.yt_vid_2)
      content_tag(:iframe, nil, src: "https://www.youtube.com/embed/#{url}?rel=0", width: 560, height: 315, frameborder: 0, allowfullscreen: true) 
      %>
    </div>
    <% end %>
    
    
    <% unless @teacher_info.yt_vid_3.nil? || @teacher_info.yt_vid_3.empty? %>
    <div class="row">
      <%= 
      url = parse_youtube(@teacher_info.yt_vid_3)
      content_tag(:iframe, nil, src: "https://www.youtube.com/embed/#{url}?rel=0", width: 560, height: 315, frameborder: 0, allowfullscreen: true) 
      %>
    </div>
    <% end %>


  </div>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    <%= render 'lessons' %>
  </div>
</div>