config/routes.rb
Rails.application.routes.draw do

  # run 'rails routes' to see what rails thinks are the routes

  root 'static_pages#a1_top'

  # you can refer to the url '/blah' in code using the method blah_path,
  # without worrying about the actual controller/action names, which are
  # defined here:
  get '/company', to: 'static_pages#b1_company'
  get '/service', to: 'static_pages#b2_service'
  get '/recruit', to: 'static_pages#b3_recruit'
  get '/terms',   to: 'static_pages#b4_terms'
  get '/privacy', to: 'static_pages#b5_privacy'
  
  get '/signup',  to: 'users#new'
  
  # get the full RESTful paths.
  resources :users
  resources :teachers
  resources :lessons
  
  get '/students', to: 'users#index_students'
  post '/buy',     to: 'users#buy'
  post '/book',    to: 'lessons#book'

  # for sessions, we don't want the entire RESTful resources, just a few
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="nav">
      <div class="container">
        <%= link_to "japaneasy.me", root_path , id: "logo"  %>
        [LOGO HERE]
        <nav>
          <div id="whoami">
            <%= render 'whoami', who: current_user %>
          </div>
            
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to t("c1_visitors"),       '#' %></li>
            <li><%= link_to t("c2_lessons"),        '#' %></li>
            <li><%= link_to t("c4_courses_fees"),     '#' %></li>
            <li><%= link_to t("c5_teachers"),      teachers_path  %></li>
            <li><%= link_to t("c6_faq"),                '#' %></li>
            <li><%= link_to t("contact_us"),            '#' %></li>
      
            <% if logged_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "My Profile", current_user.teacher? ? teacher_path(current_user.id) : user_path(current_user.id) %></li>
                  <li><%= link_to "View all Students", students_path %></li>
                  <li><%= current_user.admin? ? (link_to "Create new Teacher", new_teacher_path) : nil %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
      
      
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
                Language/言語 <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "English", locale: :en  %></li>
                <li><%= link_to "日本語",  locale: :ja  %></li>
              </ul>
            </li>
          </ul>
        </nav>
      </div>
    </header>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <div class="col-sm-9 col-xs-12">
        
        <%= yield %>
      </div>
      <div class="col-sm-3">
        <ul class="nav nav-stacked">
          <li><a href="#">D1 Reservation</a></li>
          <li><%= link_to "D2 Sign up", signup_path %></li>
          <li><a href="#">Updates</a></li>
          <li><a href="#">D3 Voices from Students</a></li>
          <li><a href="#">Blog</a></li>
        </ul>
      </div>
    </div>

    <footer>
      <div class="container">
        <ul class="nav navbar-nav">
          <li><%= link_to t("b1_company"),   company_path %></li>
          <li><%= link_to t("b2_service"),   service_path%></li>
          <li><%= link_to t("b3_recruit"),   recruit_path%></li>
          <li><%= link_to t("b4_terms"),     terms_path%></li>
          <li><%= link_to t("b5_privacy"),   privacy_path%></li>
        </ul>
      </div>
    </footer>
  
    <%= debug(params) if Rails.env.development? %>
  
  
  </body>
</html>